//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FullScreenWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(FullScreen), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("Adjust_SizeDelta", Adjust_SizeDelta);
		L.RegFunction("Adjust_InSizeDelta", Adjust_InSizeDelta);
		L.RegFunction("Adjust_Scale", Adjust_Scale);
		L.RegFunction("SetSize", SetSize);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("_method", get__method, set__method);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Adjust_SizeDelta(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			FullScreen obj = (FullScreen)ToLua.CheckObject<FullScreen>(L, 1);
			obj.Adjust_SizeDelta();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Adjust_InSizeDelta(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			FullScreen obj = (FullScreen)ToLua.CheckObject<FullScreen>(L, 1);
			obj.Adjust_InSizeDelta();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Adjust_Scale(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			FullScreen obj = (FullScreen)ToLua.CheckObject<FullScreen>(L, 1);
			obj.Adjust_Scale();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetSize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			FullScreen obj = (FullScreen)ToLua.CheckObject<FullScreen>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			obj.SetSize(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get__method(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FullScreen obj = (FullScreen)o;
			AdaptationMethod ret = obj._method;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _method on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set__method(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FullScreen obj = (FullScreen)o;
			AdaptationMethod arg0 = (AdaptationMethod)ToLua.CheckObject(L, 2, typeof(AdaptationMethod));
			obj._method = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _method on a nil value");
		}
	}
}

