//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_Playables_PlayableBehaviourWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.Playables.PlayableBehaviour), typeof(System.Object));
		L.RegFunction("OnGraphStart", OnGraphStart);
		L.RegFunction("OnGraphStop", OnGraphStop);
		L.RegFunction("OnPlayableCreate", OnPlayableCreate);
		L.RegFunction("OnPlayableDestroy", OnPlayableDestroy);
		L.RegFunction("OnBehaviourDelay", OnBehaviourDelay);
		L.RegFunction("OnBehaviourPlay", OnBehaviourPlay);
		L.RegFunction("OnBehaviourPause", OnBehaviourPause);
		L.RegFunction("PrepareData", PrepareData);
		L.RegFunction("PrepareFrame", PrepareFrame);
		L.RegFunction("ProcessFrame", ProcessFrame);
		L.RegFunction("Clone", Clone);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnGraphStart(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Playables.PlayableBehaviour obj = (UnityEngine.Playables.PlayableBehaviour)ToLua.CheckObject<UnityEngine.Playables.PlayableBehaviour>(L, 1);
			UnityEngine.Playables.Playable arg0 = StackTraits<UnityEngine.Playables.Playable>.Check(L, 2);
			obj.OnGraphStart(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnGraphStop(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Playables.PlayableBehaviour obj = (UnityEngine.Playables.PlayableBehaviour)ToLua.CheckObject<UnityEngine.Playables.PlayableBehaviour>(L, 1);
			UnityEngine.Playables.Playable arg0 = StackTraits<UnityEngine.Playables.Playable>.Check(L, 2);
			obj.OnGraphStop(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnPlayableCreate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Playables.PlayableBehaviour obj = (UnityEngine.Playables.PlayableBehaviour)ToLua.CheckObject<UnityEngine.Playables.PlayableBehaviour>(L, 1);
			UnityEngine.Playables.Playable arg0 = StackTraits<UnityEngine.Playables.Playable>.Check(L, 2);
			obj.OnPlayableCreate(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnPlayableDestroy(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Playables.PlayableBehaviour obj = (UnityEngine.Playables.PlayableBehaviour)ToLua.CheckObject<UnityEngine.Playables.PlayableBehaviour>(L, 1);
			UnityEngine.Playables.Playable arg0 = StackTraits<UnityEngine.Playables.Playable>.Check(L, 2);
			obj.OnPlayableDestroy(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnBehaviourDelay(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Playables.PlayableBehaviour obj = (UnityEngine.Playables.PlayableBehaviour)ToLua.CheckObject<UnityEngine.Playables.PlayableBehaviour>(L, 1);
			UnityEngine.Playables.Playable arg0 = StackTraits<UnityEngine.Playables.Playable>.Check(L, 2);
			UnityEngine.Playables.FrameData arg1 = StackTraits<UnityEngine.Playables.FrameData>.Check(L, 3);
			obj.OnBehaviourDelay(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnBehaviourPlay(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Playables.PlayableBehaviour obj = (UnityEngine.Playables.PlayableBehaviour)ToLua.CheckObject<UnityEngine.Playables.PlayableBehaviour>(L, 1);
			UnityEngine.Playables.Playable arg0 = StackTraits<UnityEngine.Playables.Playable>.Check(L, 2);
			UnityEngine.Playables.FrameData arg1 = StackTraits<UnityEngine.Playables.FrameData>.Check(L, 3);
			obj.OnBehaviourPlay(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnBehaviourPause(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Playables.PlayableBehaviour obj = (UnityEngine.Playables.PlayableBehaviour)ToLua.CheckObject<UnityEngine.Playables.PlayableBehaviour>(L, 1);
			UnityEngine.Playables.Playable arg0 = StackTraits<UnityEngine.Playables.Playable>.Check(L, 2);
			UnityEngine.Playables.FrameData arg1 = StackTraits<UnityEngine.Playables.FrameData>.Check(L, 3);
			obj.OnBehaviourPause(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PrepareData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Playables.PlayableBehaviour obj = (UnityEngine.Playables.PlayableBehaviour)ToLua.CheckObject<UnityEngine.Playables.PlayableBehaviour>(L, 1);
			UnityEngine.Playables.Playable arg0 = StackTraits<UnityEngine.Playables.Playable>.Check(L, 2);
			UnityEngine.Playables.FrameData arg1 = StackTraits<UnityEngine.Playables.FrameData>.Check(L, 3);
			obj.PrepareData(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PrepareFrame(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Playables.PlayableBehaviour obj = (UnityEngine.Playables.PlayableBehaviour)ToLua.CheckObject<UnityEngine.Playables.PlayableBehaviour>(L, 1);
			UnityEngine.Playables.Playable arg0 = StackTraits<UnityEngine.Playables.Playable>.Check(L, 2);
			UnityEngine.Playables.FrameData arg1 = StackTraits<UnityEngine.Playables.FrameData>.Check(L, 3);
			obj.PrepareFrame(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ProcessFrame(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			UnityEngine.Playables.PlayableBehaviour obj = (UnityEngine.Playables.PlayableBehaviour)ToLua.CheckObject<UnityEngine.Playables.PlayableBehaviour>(L, 1);
			UnityEngine.Playables.Playable arg0 = StackTraits<UnityEngine.Playables.Playable>.Check(L, 2);
			UnityEngine.Playables.FrameData arg1 = StackTraits<UnityEngine.Playables.FrameData>.Check(L, 3);
			object arg2 = ToLua.ToVarObject(L, 4);
			obj.ProcessFrame(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Clone(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.Playables.PlayableBehaviour obj = (UnityEngine.Playables.PlayableBehaviour)ToLua.CheckObject<UnityEngine.Playables.PlayableBehaviour>(L, 1);
			object o = obj.Clone();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

