--- 事件Key值定义：需要全局唯一

-- 网络相关
EVENT_NET_ONCONNECT = -1;      -- 连接成功
EVENT_NET_EXCEPTION = -102;    -- 异常掉线

--程序定义
EVENT_APPLICATION_ONFOCUS   = "EVENT_APPLICATION_ONFOCUS";   -- 获得焦点
EVENT_APPLICATION_ONQUIT    = "EVENT_APPLICATION_ONQUIT";    -- 程序退出
EVENT_APPLICATION_ONPAUSE   = "EVENT_APPLICATION_ONPAUSE";   -- 进入后台

--UI
Event_UI_ONOPEN     = "Event_UI_ONOPEN";
Event_UI_ONOPEN     = "Event_UI_ONOPEN";
Event_UI_ONDESTROY  = "Event_UI_ONDESTROY";