using UnityEngine;
using System.Collections;

public delegate bool BoolDelegate();
public delegate void VoidDelegate();
public delegate void VoidDelegateBool(bool b);
public delegate void VoidDelegateBoolString(bool b, string s);
public delegate void VoidDelegateBoolInt(bool b, int i1);
public delegate void VoidDelegateString(string s1);
public delegate void VoidDelegateStringString(string s1, string s2);
public delegate void VoidDelegateStringBool(string s1, bool b2);
public delegate void VoidDelegateStringFloat(string s1, float f2);
public delegate void VoidDelegateIntIntInt(int i1, int i2, int i3);
public delegate void VoidDelegateIntInt(int i1, int i2);
public delegate void VoidDelegateInt(int i1);
public delegate void VoidDelegateFloat(float f1);
public delegate void VoidDelegateFloatIntInt(float f1, int i1, int i2);
public delegate void VoidDelegateStringInt(string s1, int i2);
public delegate void VoidDelegateFloatInt(float f1, int i2);
public delegate void VoidDelegateFloatFloatInt(float f1, float f2, int i2);
public delegate void VoidDelegateFloatIntBool(float f1, int i2, bool b3);
public delegate void VoidDelegateFloatIntIntBool(float f1, int i2, int i3, bool b4);
public delegate void VoidDelegateFloatIntFloatBool(float f1, int i2, float i3, bool b4);
public delegate void VoidDelegateVector3(Vector3 v);
public delegate void VoidDelegateVector2(Vector2 v);
public delegate void VoidDelegateVector3Vector3(Vector3 v31, Vector3 v32);
public delegate void VoidDelegateLong(long l1);
public delegate void VoidDelegateLongInt(long s1, int i2);
public delegate void VoidDelegateLongFloat(long s1, float f1);
public delegate void VoidDelegateFloatFloatBoolString(float f1, float f2, bool b1, string s1);
